- name: Check if root superuser password already generated and saved
  become: false
  delegate_to: localhost
  stat:
    path: _terms/superuser_password
  register: stat_superuser_password

# This is wrong, we need to know when docker finished setup of lava, somehow
# watch docker-compose logs?
- name: Pause for lava to finish install
  pause:
    minutes: 1
  when: not stat_superuser_password.stat.exists

- name: Copy django_create_superuser.py
  ansible.builtin.copy:
    src: ./roles/lava/files/django_create_superuser.py
    dest: /root/

- name: Copy file inside docker container
  command: docker cp django_create_superuser.py lava-docker-compose_lava-server_1:/root
  args:
     chdir: /root

- name: create a root superuser with a random password
  command: docker-compose exec lava-server python3 /root/django_create_superuser.py
  register: superuser_result
  args:
     chdir: /root/lava-docker-compose
  when: not stat_superuser_password.stat.exists

- name: save password
  become: false
  local_action: 
    module: copy 
    content: "{{ superuser_result.stdout_lines[0] }}"
    dest: _terms/superuser_password
  when: not stat_superuser_password.stat.exists

- name: Check if root token already generated and saved
  delegate_to: localhost
  become: false
  stat:
    path: _terms/root_token
  register: stat_root_token

- name: create a root token
  command: docker-compose exec lava-server lava-server manage tokens add --user root
  register: token_result
  args:
     chdir: /root/lava-docker-compose
  when: not stat_root_token.stat.exists

- name: save root token
  become: false
  local_action: 
    module: copy 
    content: "{{ token_result.stdout_lines[0] }}"
    dest: _terms/root_token
  when: not stat_root_token.stat.exists

# This one not sure at all, i doubt executing apt update is good idea inside docker container
- name: apt update for lavacli install
  command: docker-compose exec lava-server apt update
  args:
     chdir: /root/lava-docker-compose

- name: apt update for lavacli install
  command: docker-compose exec lava-server apt install lavacli
  args:
     chdir: /root/lava-docker-compose

- name: apt install identity
  command: docker-compose exec lava-server lavacli identities add --uri http://lava-server:8000/RPC2 --token {{ token_result.stdout_lines[0] }} --username root default
  args:
     chdir: /root/lava-docker-compose
  when: not stat_root_token.stat.exists

