- name: Gather facts from new server
  setup:
    filter: ansible_default_ipv4.address

- name: Save ip address
  become: false
  local_action:
    module: copy
    content: "{{ ansible_default_ipv4.address }}"
    dest: _terms/ipaddress

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

# python-docker for debian 10
- name: Update apt and install docker-ce
  apt: update_cache=yes name={{ item }} state=latest
  loop: [ 'docker-ce', 'docker-compose', 'python3-yaml']

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: https://git.lavasoftware.org/lava/pkg/docker-compose.git
    dest: /root/lava-docker-compose

- name: Install bottle python package
  pip:
    name: docker-compose
    executable: pip3

# Debian 11 docker service fails and need restart
- name: Reload docker service (please wait!)
  retries: 20
  delay: 5
  register: result
  until: result.failed == false
  ansible.builtin.systemd:
    name: docker.service
    state: restarted

- name: Docker compose pull
  command: docker-compose pull
  args:
    chdir: /root/lava-docker-compose

- name: Docker compose build
  command: docker-compose build
  args:
    chdir: /root/lava-docker-compose

- name: Docker compose up
  command: docker-compose up -d
  args:
    chdir: /root/lava-docker-compose

- import_tasks: lava-secrets.yaml
- import_tasks: lava-device-qemu0.yaml
